const MONGO_USER = 'test';
const MONGO_PASS = 'test';
const MONGO_SERVER = 'ds149030.mlab.com:49030/heroku_00vlg1jl';

const MONGO_URL = `mongodb://${MONGO_USER && MONGO_PASS ? `${MONGO_USER}:${MONGO_PASS}@` : ''}${MONGO_SERVER}`;
const SERVER_PORT = 3000;

//SECURITY
ACCOUNT_SECURITY_TOKEN = 'ALL THE THINGS WE DO FOR LOVE';
ACCOUNT_TOKEN_TIME_EXPIRATION = 60*60*24*30; //30 days

module.exports = {
  SERVER_PORT,
  MONGO_URL,

  ACCOUNT_SECURITY_TOKEN,
  ACCOUNT_TOKEN_TIME_EXPIRATION
}